openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is the Api documentation for Traveler site, platform where travelers share their stories, experiences, and adventures. The API enables user management, story creation, media uploads, and community interactions.
tags:
  - name: Auth
    description: Authorization routes for user registration, login, logout, and password management.
  - name: Users
    description: Operations about users, including profile management and retrieval.
  - name: Stories
    description: Operations related to traveler stories, including creation, retrieval, updating, and deletion.

servers:
  - url: https://project-codecraft-backend.onrender.com/api
    description: Production server (Render)
  - url: http://localhost:3000/api
    description: Local development server

components:
  schemas:
    user:
      $ref: '../swagger/components/schemas/user.yaml'
    story:
      $ref: '../swagger/components/schemas/story.yaml'
  responses:
    '200':
      $ref: '../swagger/components/responses/200.yaml'
    '201':
      $ref: '../swagger/components/responses/201.yaml'
    '204':
      $ref: '../swagger/components/responses/204.yaml'
    '400':
      $ref: '../swagger/components/responses/400.yaml'
    '401':
      $ref: '../swagger/components/responses/401.yaml'
    '403':
      $ref: '../swagger/components/responses/403.yaml'
    '404':
      $ref: '../swagger/components/responses/404.yaml'
    '409':
      $ref: '../swagger/components/responses/409.yaml'
  securitySchemes:
    $ref: '../swagger/components/securitySchemes.yaml'
paths:
  /auth/register:
    $ref: '../swagger/paths/auth/register/post.yaml'
  /auth/login:
    $ref: '../swagger/paths/auth/login/post.yaml'
  /auth/logout:
    $ref: '../swagger/paths/auth/logout/post.yaml'
  /auth/refresh:
    $ref: '../swagger/paths/auth/refresh/post.yaml'
  /auth/send-reset-email:
    $ref: '../swagger/paths/auth/send-reset-email/post.yaml'
  /auth/reset-password:
    $ref: '../swagger/paths/auth/reset-password/post.yaml'

  /users:
    $ref: '../swagger/paths/users/get.yaml'
  /users/current:
    $ref: '../swagger/paths/users/current/get.yaml'
  /users/{userId}:
    $ref: '../swagger/paths/users/{userId}/get.yaml'
  /users/updateUser:
    $ref: '../swagger/paths/users/updateUser/patch.yaml'
  /users/avatar:
    $ref: '../swagger/paths/users/avatar/patch.yaml'
  /users/saved/{storyId}:
    post:
      $ref: '../swagger/paths/users/saved/{storyId}/post.yaml'
    delete:
      $ref: '../swagger/paths/users/saved/{storyId}/delete.yaml'

  /stories:
    get:
      $ref: '../swagger/paths/stories/get.yaml'
    post:
      $ref: '../swagger/paths/stories/post.yaml'
  /stories/{storyId}:
    get:
      $ref: '../swagger/paths/stories/{storyId}/get.yaml'
    patch:
      $ref: '../swagger/paths/stories/{storyId}/patch.yaml'
    delete:
      $ref: '../swagger/paths/stories/{storyId}/delete.yaml'
