openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <опис вашого додатку>
tags:
  - name: Public routers
    description: Публічні маршрути доступні без авторизвції
servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-kxks.onrender.com
paths:
  /users:
    get:
      $ref: ../swagger/paths/users/get.yaml
  /users/{userId}:
    get:
      $ref: ../swagger/paths/users/{userId}/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
