openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: <опис вашого додатку>
tags:
  - name: Public routers
    description: Публічні маршрути доступні без авторизвції
  - name: Contacts
    description: Operations about users.
  - name: Stories
    description: Operations related to travel stories.

servers:
  - url: http://localhost:3000
  # - url: https://nodejs-hw-mongodb-kxks.onrender.com
paths:
  /users:
    get:
      $ref: ../swagger/paths/users/get.yaml
  /users/{userId}:
    get:
      $ref: ../swagger/paths/users/{userId}/get.yaml
  /users/current:
    $ref: ../swagger/paths/users/current/get.yaml
  /users/updateUser:
    $ref: ../swagger/paths/users/updateUser/patch.yaml
  /user/saved/{storyId}:
    post:
      $ref: '../swagger/paths/users/saved/{storyId}/post.yaml'
    delete:
      $ref: '../swagger/paths/users/saved/{storyId}/delete.yaml'
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login/post.yaml
  /stories:
    post:
      $ref: '../swagger/paths/stories/post.yaml'
  /stories/{storyId}:
    patch:
      $ref: '../swagger/paths/stories/{storyId}/patch.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
